const mongoose = require('mongoose');

const InvoiceSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true
    },
    providerName: {
      type: String,
      required: true,
      lowercase: true
    }, // e.g. "netflix", "spotify", "adobe_creative"
    amount: {
      type: Number,
      required: true
    }, // Total paid in kobo
    status: {
      type: String,
      enum: ['paid', 'pending', 'failed'],
      default: 'pending'
    },
    reference: { type: String, required: true, unique: true }, // Paystack checkout reference string
    invoiceUrl: { type: String }, // Optional PDF link generated by Paystack
    paidAt: { type: Date }
  },
  { timestamps: true }
);

module.exports = mongoose.model('Invoice', InvoiceSchema);
